# Generated by Django 2.2.6 on 2019-10-04 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retiro', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_art', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=10)),
                ('fecha_llegada', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('accesorio', models.ManyToManyField(to='producto.accesorio')),
                ('retiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retiro.retiro')),
            ],
        ),
        migrations.DeleteModel(
            name='Artículo',
        ),
    ]
